### ISSUE TITLE
TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by sq3** [wayneashleyberry/wunderlist-cli#42] opened 2015-07-03 11:37 UTC
After installing the tool via npm, I've got the following problem. It comes every time I use wunderline with any option for example "inbox"

```
 $ wunderline inbox
/usr/local/lib/node_modules/wunderline/util/get-inbox.js:27
    var lists = body.filter(function (item) {
                     ^
TypeError: undefined is not a function
    at Request._callback (/usr/local/lib/node_modules/wunderline/util/get-inbox.js:27:22)
    at Request.self.callback (/usr/local/lib/node_modules/wunderline/node_modules/request/request.js:197:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/wunderline/node_modules/request/request.js:1050:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/wunderline/node_modules/request/request.js:996:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

**Comment by wayneashleyberry** [comment] 2015-07-03 11:52
Duplicate of https://github.com/we-are-next/wunderline/issues/40

I'm going to be adding proper authentication errors soon (see https://github.com/we-are-next/wunderline/issues/41)

**Closed as completed by wayneashleyberry** 2015-07-03 11:52 UTC
