### ISSUE TITLE
Getting error while authenticating wunderline.

### ISSUE THREAD

**Issue by deepak365** [wayneashleyberry/wunderlist-cli#93] opened 2016-07-30 03:17 UTC
Steps to reproduce :
1. `wunderline auth` 
2.  Add Client ID
3.  Add Access token

Error : 

```
/usr/local/lib/node_modules/wunderline/wunderline-auth.js:50
    console.log('Thanks ' + body.name.split(' ')[0] + ', Wunderline has been authenticated.')
                                     ^

TypeError: Cannot read property 'split' of undefined
    at Request._callback (/usr/local/lib/node_modules/wunderline/wunderline-auth.js:50:38)
    at Request.self.callback (/usr/local/lib/node_modules/wunderline/node_modules/request/request.js:187:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/wunderline/node_modules/request/request.js:1044:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/wunderline/node_modules/request/request.js:965:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
```

Node version : node -v  v4.4.5

**Comment by Thor77** [comment] 2016-09-23 14:05
Are you running the latest version of wunderline? (There were some updates in error-handling recently)

**Comment by Thor77** [comment] 2016-10-16 16:58
Closing this due to missing feedback.
Feel free to reopen if you can reproduce this on a recent version @deepak365.

**Closed as completed by Thor77** 2016-10-16 16:58 UTC
